[package]
name = "wiki"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
#either = "1.14.0"
reqwest = {version = "0.12.12", features = ["blocking", "json"] }
serde = "1.0.218"
serde_json = "1.0.139"
